Add Nix files and commit `Cargo.lock`
cryspen/libcrux pull request #300
Opened 2024-06-05 14:02 UTC by pnmadelaine

2024-06-06 12:07 UTC, pnmadelaine commented
I disabled LTO in the Nix build as it causes the build to fail. Am I missing something, is there a specific toolchain to use? I am using `gcc` and `ld`.

2024-06-06 13:13 UTC, pnmadelaine commented
using mold instead of ld seems to fix the issue!

2024-06-10 13:59 UTC, franziskuskiefer requested changes
Thanks, generally looks good except for that one change.

2024-06-10 13:59 UTC, franziskuskiefer commented on libcrux-ml-kem/c/CMakeLists.txt
> -FetchContent_Populate(benchmark
Where does this change come from? It doesn't look right.

2024-06-10 16:15 UTC, pnmadelaine commented
@franziskuskiefer I'll just continue the conversation here as github seems to double all my comments on the code (?)

I think you meant using `fetch_package` was not right because it required installing `benchmark` manually? I used `FetchContent_Declare` instead, is that okay with you?

2024-06-11 08:25 UTC, W95Psp commented
(quoting myself from https://github.com/cryspen/bertie/pull/118, since it's the same concern)
> I see no point in not committing flake.lock, of we don't commit flake.lock, we should drop the nix expressions altogether. The nix job you added will check the nix expressions are up to date as code changes, that's all we need imo. Locked flakes are especially useful to make sure we'll be able to build the project in the future.

2024-06-11 14:12 UTC, pnmadelaine commented
converting to draft as this is currently broken after updating

2024-06-11 19:29 UTC, protz approved these changes

2024-06-12 08:28 UTC, franziskuskiefer approved these changes

2024-06-12 08:56 UTC, merged