Add feature `kyber` for Round 3 Kyber API
cryspen/libcrux pull request #327
Opened 2024-06-20 08:26 UTC by jschneider-bensch

This PR fixes #325, by making available `kyber{512,768,1024}`  modules with their own `encapsulate` and `decapsulate` behind the `kyber` feature, in addition to the regular ML-KEM API.
The differences in Kyber compared to ML-KEM are
- a hash of the initial encapsulation randomness is used instead of using the randomness directly
- the derivation of the shared secret includes a hash of the ciphertext

c.f. [FIPS 203 (Draft), section 1.3](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.ipd.pdf).

Further, the hybrid KEMs in `libcrux-kem` are now available in both variants as well.

2024-06-24 12:38 UTC, franziskuskiefer requested changes
I need to figure out how to make eurydice happy here. But I left some comments to be addressed.

2024-06-24 15:08 UTC, franziskuskiefer reviewed
With [this change](https://github.com/cryspen/libcrux/commit/8cdead9d4e2f022fbe794f5b3dd59c5df3ff0797) C extraction should work again. Looks like eurydice prefers the trait bounds on the functions. Let's do that for now.

2024-06-26 09:58 UTC, jschneider-bensch commented on libcrux-ml-kem/tests/kyber.rs
> +fn kyber768() {
I've added KAT generation for all parameter sets of Kyber, as we have it for ML-KEM as well.

2024-06-26 12:57 UTC, franziskuskiefer approved these changes
Thanks, lgtm. But we should also update the C code. And it looks like that extraction is broken again 😬

2024-06-26 14:15 UTC, merged