Changed KyberFieldElement from a struct to a type alias for an i16.
cryspen/libcrux pull request #41
Opened 2023-08-16 21:54 UTC by xvzcf

Also removed the `FieldElement` interface, and the generic PolynomialRingElement interface.

2023-08-17 07:38 UTC, franziskuskiefer requested changes
Thanks, looks good. Only a few nits.

2023-08-17 07:38 UTC, franziskuskiefer commented on src/kem/kyber768/ntt.rs
> +                    let t = fe_mul(re[j + layer], ZETAS[zeta_i]);
For readability, we might want to implement the operators. But let's keep this for now.

2023-08-17 14:32 UTC, xvzcf commented on src/kem/kyber768/arithmetic.rs
Added a TODO to add more comments

2023-08-18 07:27 UTC, franziskuskiefer approved these changes
Thanks :shipit:

2023-08-18 13:56 UTC, merged