Add randomised APIs to ml-kem
cryspen/libcrux pull request #546
Opened 2024-08-30 07:39 UTC by franziskuskiefer

2024-09-02 14:43 UTC, jschneider-bensch requested changes
Looks good to me, with tiny doc nits :+1:

2024-09-02 14:43 UTC, jschneider-bensch commented on libcrux-ml-kem/src/kem/kyber/kyber1024.rs
>  /// Returns `Some(public_key)` if valid, and `None` otherwise.
```suggestion
/// Returns `true` if valid, and `false` otherwise.
```

2024-09-02 14:43 UTC, jschneider-bensch commented on libcrux-ml-kem/src/kem/kyber/kyber512.rs
>  /// Returns `Some(public_key)` if valid, and `None` otherwise.
```suggestion
/// Returns `true` if valid, and `false` otherwise.
```

2024-09-02 14:43 UTC, jschneider-bensch commented on libcrux-ml-kem/src/kem/kyber/kyber768.rs
>  /// Returns `Some(public_key)` if valid, and `None` otherwise.
```suggestion
/// Returns `true` if valid, and `false` otherwise.
```

2024-09-02 15:12 UTC, franziskuskiefer reviewed
Ah thanks. Copy pasta

2024-09-03 06:32 UTC, jschneider-bensch commented
Huh, somehow the extraction diff fails now because `.gitignore` is missing in the extracted version. In the extract jobs, `actions/upload-artifact@v4` has option `include-hidden-files` set to `false` so it makes sense that the `.gitignore` should be ignored. It must have been included before though, since that job would have had to fail every time previously, otherwise. Indeed, on an earlier run of that job the action did not have this option: https://github.com/cryspen/libcrux/actions/runs/10636686836/job/29488994163

2024-09-03 06:33 UTC, jschneider-bensch approved these changes

2024-09-03 06:34 UTC, jschneider-bensch commented
Ah, I see, it was [announced as a breaking change](https://github.com/actions/upload-artifact/issues/602). Still a bit weird to have that without a version bump

2024-09-03 06:38 UTC, franziskuskiefer commented
> Ah, I see, it was [announced as a breaking change](https://github.com/actions/upload-artifact/issues/602). Still a bit weird to have that without a version bump

🙄 looks like everyone is annoyed by this. @jschneider-bensch would you mind pushing a fix to this branch?

2024-09-03 06:42 UTC, jschneider-bensch commented
Ah sorry, I would have, but I've already pushed a fix to it's own PR #555

2024-09-03 12:00 UTC, merged